name: MLB Data Analyzer Frontend CD

on:
  push:
    branches:
      - main
      - master
  workflow_run:
    workflows: [MLB Data Analyzer Frontend CI]
    types:
      - completed

jobs:
    build-and-deploy:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4

        - uses: actions/setup-node@v4
          with:
            node-version: 20.11.1
            cache: 'npm'

        - name: Clean install npm packages
          run: npm ci

        - name: Docker build and run container
          run: |
            docker build . -t "mlb-frontend-server"
            sudo docker run -p 3000:3000 mlb-frontend-server:latest

        - name: Login to Dockerhub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Build and Push Container
          uses: docker/build-push-action@v3
          with:
            push: true
            tags: webguy1979/mlb-frontend-server:latest

        - name: Sleep for 10 seconds
          run: sleep 10s
          shell: bash

        - name: Deploy to Portainer 3
          uses: rrennoir/portainer-stack@v2
          with:
            portainerUrl: ${{ secrets.PORTAINER_URL }}
            portainerApiKey: ${{ secrets.PORTAINER_ACCES_TOKEN }}
            portainerEndpointId: 2
            stackName: mlb-frontend-server
            stackType: 2
            composeFile: ./docker-compose.yml