name: MLB Data Analyzer Frontend CI

on:
  pull_request:
    branches:
      - '**'

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20.11.1
          cache: 'npm'

      - name: Clean install npm packages
        run: npm ci

      - name: Run tests
        run: npm run test
